name: Build Package
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

    - name: 设置 Bun
      uses: oven-sh/setup-bun@v2

    - name: 构建
      run: |
        bun install
        bun run build
        mkdir -p ${{ runner.temp }}/temp/
        cp -r package.json README.md dist ${{ runner.temp }}/temp/

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.beta-version.outputs.package_short_name }}
        path: ${{ runner.temp }}/temp/