name: Build Package
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
        repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

    - name: 设置 pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: true

    - name: 构建
      run: |
        pnpm build
        pnpm pkg delete devDependencies
        mkdir -p ${{ runner.temp }}/temp/
        cp -r package.json README.md dist ${{ runner.temp }}/temp/

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: puppeteer-core
        path: ${{ runner.temp }}/temp/